//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen -n |core.xsd=MentorLake.Gir.Core -n |c.xsd=MentorLake.Gir.C -n |glib.xsd=MentorLake.Gir.GLib -n |xml.xsd=MentorLake.Gir.Xml --o GirTypes --cn --uc -ct System.Collections.Generic.List`1 --sf --nh ./core.xsd
namespace MentorLake.Gir.Core
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("array", Namespace="http://www.gtk.org/introspection/core/1.0", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("array", Namespace="http://www.gtk.org/introspection/core/1.0")]
    public partial class Array
    {
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlElementAttribute("type", Type=typeof(Type), Namespace="http://www.gtk.org/introspection/core/1.0")]
        [XmlElementAttribute("array", Type=typeof(Array), Namespace="http://www.gtk.org/introspection/core/1.0")]
        [XmlElementAttribute("AnyType")]
        public object AnyType { get; set; }
        
        /// <summary>
        /// <para>name of the array type</para>
        /// </summary>
        [DescriptionAttribute("name of the array type")]
        [XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>Binary attribute, true if the last element of the array is zero. For example, in an array of pointers, the last pointer would be NULL</para>
        /// </summary>
        [DescriptionAttribute("Binary attribute, true if the last element of the array is zero. For example, in " +
            "an array of pointers, the last pointer would be NULL")]
        [XmlAttributeAttribute("zero-terminated")]
        public ArrayZeroTerminated ZeroTerminated { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ZeroTerminated property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ZeroTerminatedSpecified { get; set; }
        
        /// <summary>
        /// <para>size of an array of predetermined fixed size. For example a C array declared as char arr[5].</para>
        /// </summary>
        [DescriptionAttribute("size of an array of predetermined fixed size. For example a C array declared as c" +
            "har arr[5].")]
        [XmlAttributeAttribute("fixed-size")]
        public string FixedSize { get; set; }
        
        /// <summary>
        /// <para>Binary attribute which is "0" (false) if the element is not introspectable. It doesn't exist in the bindings, due in general to missing information in the annotations in the original C code</para>
        /// </summary>
        [DescriptionAttribute("Binary attribute which is \"0\" (false) if the element is not introspectable. It do" +
            "esn\'t exist in the bindings, due in general to missing information in the annota" +
            "tions in the original C code")]
        [XmlAttributeAttribute("introspectable")]
        public ArrayIntrospectable Introspectable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Introspectable property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool IntrospectableSpecified { get; set; }
        
        /// <summary>
        /// <para>0-based index of parameter element that specifies the length of the array</para>
        /// </summary>
        [DescriptionAttribute("0-based index of parameter element that specifies the length of the array")]
        [XmlAttributeAttribute("length")]
        public string Length { get; set; }
        
        [XmlAttributeAttribute("type", Namespace="http://www.gtk.org/introspection/c/1.0", Form=XmlSchemaForm.Qualified)]
        public string Type { get; set; }
    }
}
