//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen -n |core.xsd=MentorLake.Gir.Core -n |c.xsd=MentorLake.Gir.C -n |glib.xsd=MentorLake.Gir.GLib -n |xml.xsd=MentorLake.Gir.Xml --o GirTypes --cn --uc -ct System.Collections.Generic.List`1 --sf --nh ./core.xsd
namespace MentorLake.Gir.Core
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("docsection", Namespace="http://www.gtk.org/introspection/core/1.0", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("docsection", Namespace="http://www.gtk.org/introspection/core/1.0")]
    public partial class Docsection : IDocElements
    {
        
        [XmlIgnoreAttribute()]
        private List<DocVersion> _docVersion;
        
        [XmlElementAttribute("doc-version")]
        public List<DocVersion> DocVersion
        {
            get
            {
                return _docVersion;
            }
            private set
            {
                _docVersion = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DocVersion collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool DocVersionSpecified
        {
            get
            {
                return (this.DocVersion.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Docsection" /> class.</para>
        /// </summary>
        public Docsection()
        {
            this._docVersion = new List<DocVersion>();
            this._docStability = new List<DocStability>();
            this._doc = new List<Doc>();
            this._docDeprecated = new List<DocDeprecated>();
            this._sourcePosition = new List<SourcePosition>();
        }
        
        [XmlIgnoreAttribute()]
        private List<DocStability> _docStability;
        
        [XmlElementAttribute("doc-stability")]
        public List<DocStability> DocStability
        {
            get
            {
                return _docStability;
            }
            private set
            {
                _docStability = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DocStability collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool DocStabilitySpecified
        {
            get
            {
                return (this.DocStability.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<Doc> _doc;
        
        [XmlElementAttribute("doc")]
        public List<Doc> Doc
        {
            get
            {
                return _doc;
            }
            private set
            {
                _doc = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Doc collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool DocSpecified
        {
            get
            {
                return (this.Doc.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<DocDeprecated> _docDeprecated;
        
        [XmlElementAttribute("doc-deprecated")]
        public List<DocDeprecated> DocDeprecated
        {
            get
            {
                return _docDeprecated;
            }
            private set
            {
                _docDeprecated = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the DocDeprecated collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool DocDeprecatedSpecified
        {
            get
            {
                return (this.DocDeprecated.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<SourcePosition> _sourcePosition;
        
        [XmlElementAttribute("source-position")]
        public List<SourcePosition> SourcePosition
        {
            get
            {
                return _sourcePosition;
            }
            private set
            {
                _sourcePosition = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SourcePosition collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SourcePositionSpecified
        {
            get
            {
                return (this.SourcePosition.Count != 0);
            }
        }
        
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
}
