//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen -n |core.xsd=MentorLake.Gir.Core -n |c.xsd=MentorLake.Gir.C -n |glib.xsd=MentorLake.Gir.GLib -n |xml.xsd=MentorLake.Gir.Xml --o GirTypes --cn --uc -ct System.Collections.Generic.List`1 --sf --nh ./core.xsd
namespace MentorLake.Gir.Core
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    /// <summary>
    /// <para>give the stability of the documentation</para>
    /// </summary>
    [DescriptionAttribute("give the stability of the documentation")]
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("doc-stability", Namespace="http://www.gtk.org/introspection/core/1.0", AnonymousType=true)]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("doc-stability", Namespace="http://www.gtk.org/introspection/core/1.0")]
    public partial class DocStability : IWhitespace
    {
        
        [XmlAttributeAttribute("space", Namespace="http://www.w3.org/XML/1998/namespace", Form=XmlSchemaForm.Qualified)]
        public MentorLake.Gir.Xml.Space Space { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Space property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool SpaceSpecified { get; set; }
        
        [XmlAttributeAttribute("whitespace", Namespace="http://www.w3.org/XML/1998/namespace", Form=XmlSchemaForm.Qualified)]
        public MentorLake.Gir.Xml.Whitespace Whitespace { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Whitespace property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool WhitespaceSpecified { get; set; }
        
        [XmlTextAttribute()]
        public string[] Text { get; set; }
    }
}
