//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen -n |core.xsd=MentorLake.Gir.Core -n |c.xsd=MentorLake.Gir.C -n |glib.xsd=MentorLake.Gir.GLib -n |xml.xsd=MentorLake.Gir.Xml --o GirTypes --cn --uc -ct System.Collections.Generic.List`1 --sf --nh ./core.xsd
namespace MentorLake.Gir.Core
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("union", Namespace="http://www.gtk.org/introspection/core/1.0")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("union", Namespace="http://www.gtk.org/introspection/core/1.0")]
    public partial class Union : InfoElements, IInfoAttrs, MentorLake.Gir.GLib.ITypeName3, MentorLake.Gir.GLib.IGetType3
    {
        
        [XmlIgnoreAttribute()]
        private List<Field> _field;
        
        [XmlElementAttribute("field")]
        public List<Field> Field
        {
            get
            {
                return _field;
            }
            private set
            {
                _field = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Field collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool FieldSpecified
        {
            get
            {
                return (this.Field.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Union" /> class.</para>
        /// </summary>
        public Union()
        {
            this._field = new List<Field>();
            this._constructor = new List<Constructor>();
            this._method = new List<Method>();
            this._methodInline = new List<MethodInline>();
            this._function = new List<BaseFunction>();
            this._functionInline = new List<FunctionInline>();
            this._record = new List<Record>();
        }
        
        [XmlIgnoreAttribute()]
        private List<Constructor> _constructor;
        
        [XmlElementAttribute("constructor")]
        public List<Constructor> Constructor
        {
            get
            {
                return _constructor;
            }
            private set
            {
                _constructor = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Constructor collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool ConstructorSpecified
        {
            get
            {
                return (this.Constructor.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<Method> _method;
        
        [XmlElementAttribute("method")]
        public List<Method> Method
        {
            get
            {
                return _method;
            }
            private set
            {
                _method = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Method collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool MethodSpecified
        {
            get
            {
                return (this.Method.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<MethodInline> _methodInline;
        
        [XmlElementAttribute("method-inline")]
        public List<MethodInline> MethodInline
        {
            get
            {
                return _methodInline;
            }
            private set
            {
                _methodInline = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the MethodInline collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool MethodInlineSpecified
        {
            get
            {
                return (this.MethodInline.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<BaseFunction> _function;
        
        [XmlElementAttribute("function")]
        public List<BaseFunction> Function
        {
            get
            {
                return _function;
            }
            private set
            {
                _function = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Function collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool FunctionSpecified
        {
            get
            {
                return (this.Function.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<FunctionInline> _functionInline;
        
        [XmlElementAttribute("function-inline")]
        public List<FunctionInline> FunctionInline
        {
            get
            {
                return _functionInline;
            }
            private set
            {
                _functionInline = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FunctionInline collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool FunctionInlineSpecified
        {
            get
            {
                return (this.FunctionInline.Count != 0);
            }
        }
        
        [XmlIgnoreAttribute()]
        private List<Record> _record;
        
        [XmlElementAttribute("record")]
        public List<Record> Record
        {
            get
            {
                return _record;
            }
            private set
            {
                _record = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Record collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool RecordSpecified
        {
            get
            {
                return (this.Record.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>Binary attribute which is "0" (false) if the element is not introspectable. It doesn't exist in the bindings, due in general to missing information in the annotations in the original C code</para>
        /// </summary>
        [DescriptionAttribute("Binary attribute which is \"0\" (false) if the element is not introspectable. It do" +
            "esn\'t exist in the bindings, due in general to missing information in the annota" +
            "tions in the original C code")]
        [XmlAttributeAttribute("introspectable")]
        public IInfoAttrsIntrospectable Introspectable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Introspectable property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool IntrospectableSpecified { get; set; }
        
        /// <summary>
        /// <para>Binary attribute which is "1" (true) if the element has been deprecated</para>
        /// </summary>
        [DescriptionAttribute("Binary attribute which is \"1\" (true) if the element has been deprecated")]
        [XmlAttributeAttribute("deprecated")]
        public IInfoAttrsDeprecated Deprecated { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Deprecated property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool DeprecatedSpecified { get; set; }
        
        /// <summary>
        /// <para>Version number from which this element is deprecated</para>
        /// </summary>
        [DescriptionAttribute("Version number from which this element is deprecated")]
        [XmlAttributeAttribute("deprecated-version")]
        public string DeprecatedVersion { get; set; }
        
        /// <summary>
        /// <para>version number of an element</para>
        /// </summary>
        [DescriptionAttribute("version number of an element")]
        [XmlAttributeAttribute("version")]
        public string Version { get; set; }
        
        /// <summary>
        /// <para>give the statibility status of the element. Can take the values "Stable", "Unstable" or "Private"</para>
        /// </summary>
        [DescriptionAttribute("give the statibility status of the element. Can take the values \"Stable\", \"Unstab" +
            "le\" or \"Private\"")]
        [XmlAttributeAttribute("stability")]
        public string Stability { get; set; }
        
        /// <summary>
        /// <para>name of the union</para>
        /// </summary>
        [DescriptionAttribute("name of the union")]
        [XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [XmlAttributeAttribute("type", Namespace="http://www.gtk.org/introspection/c/1.0", Form=XmlSchemaForm.Qualified)]
        public string Type { get; set; }
        
        [XmlAttributeAttribute("symbol-prefix", Namespace="http://www.gtk.org/introspection/c/1.0", Form=XmlSchemaForm.Qualified)]
        public string SymbolPrefix { get; set; }
        
        /// <summary>
        /// <para>GObject compatible type name</para>
        /// </summary>
        [DescriptionAttribute("GObject compatible type name")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("type-name", Namespace="http://www.gtk.org/introspection/glib/1.0", Form=XmlSchemaForm.Qualified)]
        public string TypeName { get; set; }
        
        /// <summary>
        /// <para>function to retrieve the GObject compatible type of the element</para>
        /// </summary>
        [DescriptionAttribute("function to retrieve the GObject compatible type of the element")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("get-type", Namespace="http://www.gtk.org/introspection/glib/1.0", Form=XmlSchemaForm.Qualified)]
        public string GetType { get; set; }
        
        /// <summary>
        /// <para>Name of the function used to copy the union</para>
        /// </summary>
        [DescriptionAttribute("Name of the function used to copy the union")]
        [XmlAttributeAttribute("copy-function")]
        public string CopyFunction { get; set; }
        
        /// <summary>
        /// <para>Name of the function used to free the union</para>
        /// </summary>
        [DescriptionAttribute("Name of the function used to free the union")]
        [XmlAttributeAttribute("free-function")]
        public string FreeFunction { get; set; }
    }
}
