//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1174.0 using the following command:
// xscgen -n |core.xsd=MentorLake.Gir.Core -n |c.xsd=MentorLake.Gir.C -n |glib.xsd=MentorLake.Gir.GLib -n |xml.xsd=MentorLake.Gir.Xml --o GirTypes --cn --uc -ct System.Collections.Generic.List`1 --sf --nh ./core.xsd
namespace MentorLake.Gir.GLib
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Diagnostics;
    using System.Xml;
    using System.Xml.Schema;
    using System.Xml.Serialization;
    
    
    [GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1174.0")]
    [SerializableAttribute()]
    [XmlTypeAttribute("boxed", Namespace="http://www.gtk.org/introspection/glib/1.0")]
    [DebuggerStepThroughAttribute()]
    [DesignerCategoryAttribute("code")]
    [XmlRootAttribute("boxed", Namespace="http://www.gtk.org/introspection/glib/1.0")]
    public partial class Boxed : MentorLake.Gir.Core.InfoElements, MentorLake.Gir.Core.IInfoAttrs
    {
        
        [XmlIgnoreAttribute()]
        private List<MentorLake.Gir.Core.BaseFunction> _function;
        
        [XmlElementAttribute("function", Namespace="http://www.gtk.org/introspection/core/1.0")]
        public List<MentorLake.Gir.Core.BaseFunction> Function
        {
            get
            {
                return _function;
            }
            private set
            {
                _function = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Function collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool FunctionSpecified
        {
            get
            {
                return (this.Function.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Boxed" /> class.</para>
        /// </summary>
        public Boxed()
        {
            this._function = new List<MentorLake.Gir.Core.BaseFunction>();
            this._functionInline = new List<MentorLake.Gir.Core.FunctionInline>();
        }
        
        [XmlIgnoreAttribute()]
        private List<MentorLake.Gir.Core.FunctionInline> _functionInline;
        
        [XmlElementAttribute("function-inline", Namespace="http://www.gtk.org/introspection/core/1.0")]
        public List<MentorLake.Gir.Core.FunctionInline> FunctionInline
        {
            get
            {
                return _functionInline;
            }
            private set
            {
                _functionInline = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FunctionInline collection is empty.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool FunctionInlineSpecified
        {
            get
            {
                return (this.FunctionInline.Count != 0);
            }
        }
        
        /// <summary>
        /// <para>Binary attribute which is "0" (false) if the element is not introspectable. It doesn't exist in the bindings, due in general to missing information in the annotations in the original C code</para>
        /// </summary>
        [DescriptionAttribute("Binary attribute which is \"0\" (false) if the element is not introspectable. It do" +
            "esn\'t exist in the bindings, due in general to missing information in the annota" +
            "tions in the original C code")]
        [XmlAttributeAttribute("introspectable")]
        public MentorLake.Gir.Core.IInfoAttrsIntrospectable Introspectable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Introspectable property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool IntrospectableSpecified { get; set; }
        
        /// <summary>
        /// <para>Binary attribute which is "1" (true) if the element has been deprecated</para>
        /// </summary>
        [DescriptionAttribute("Binary attribute which is \"1\" (true) if the element has been deprecated")]
        [XmlAttributeAttribute("deprecated")]
        public MentorLake.Gir.Core.IInfoAttrsDeprecated Deprecated { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Deprecated property is specified.</para>
        /// </summary>
        [XmlIgnoreAttribute()]
        public bool DeprecatedSpecified { get; set; }
        
        /// <summary>
        /// <para>Version number from which this element is deprecated</para>
        /// </summary>
        [DescriptionAttribute("Version number from which this element is deprecated")]
        [XmlAttributeAttribute("deprecated-version")]
        public string DeprecatedVersion { get; set; }
        
        /// <summary>
        /// <para>version number of an element</para>
        /// </summary>
        [DescriptionAttribute("version number of an element")]
        [XmlAttributeAttribute("version")]
        public string Version { get; set; }
        
        /// <summary>
        /// <para>give the statibility status of the element. Can take the values "Stable", "Unstable" or "Private"</para>
        /// </summary>
        [DescriptionAttribute("give the statibility status of the element. Can take the values \"Stable\", \"Unstab" +
            "le\" or \"Private\"")]
        [XmlAttributeAttribute("stability")]
        public string Stability { get; set; }
        
        /// <summary>
        /// <para>GObject compatible type name of the boxed type</para>
        /// </summary>
        [DescriptionAttribute("GObject compatible type name of the boxed type")]
        [RequiredAttribute(AllowEmptyStrings=true)]
        [XmlAttributeAttribute("name", Namespace="http://www.gtk.org/introspection/glib/1.0", Form=XmlSchemaForm.Qualified)]
        public string Name { get; set; }
        
        [XmlAttributeAttribute("symbol-prefix", Namespace="http://www.gtk.org/introspection/c/1.0", Form=XmlSchemaForm.Qualified)]
        public string SymbolPrefix { get; set; }
        
        /// <summary>
        /// <para>GObject compatible type name of the boxed type</para>
        /// </summary>
        [DescriptionAttribute("GObject compatible type name of the boxed type")]
        [XmlAttributeAttribute("type-name", Namespace="http://www.gtk.org/introspection/glib/1.0", Form=XmlSchemaForm.Qualified)]
        public string TypeName { get; set; }
        
        /// <summary>
        /// <para>Function to get the GObject compatible type of the boxed type</para>
        /// </summary>
        [DescriptionAttribute("Function to get the GObject compatible type of the boxed type")]
        [XmlAttributeAttribute("get-type", Namespace="http://www.gtk.org/introspection/glib/1.0", Form=XmlSchemaForm.Qualified)]
        public string GetType { get; set; }
    }
}
